# Config file for automatic testing at travis-ci.org

sudo: required
dist: xenial
language: python

matrix:
    include:
        env: TOX_ENV=py35-pytest6
      - python: 3.6
        env: TOX_ENV=py36-pytest5
      - python: 3.6
        env: TOX_ENV=py36-pytest6
      - python: 3.7
        env: TOX_ENV=py37-pytest5
      - python: 3.7
        env: TOX_ENV=py37-pytest6
      - python: 3.8
        env: TOX_ENV=py38-pytest5
      - python: 3.8
        env: TOX_ENV=py38-pytest6
      - python: 3.9
        env: TOX_ENV=py39-pytest5
      - python: 3.9
        env: TOX_ENV=py39-pytest6
      - python: 3.9
        env: TOX_ENV=flake8

install:
  - pip install tox

script:
  - tox -r -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
